### ISSUE TITLE
Hoe kun je google fonts gebruiken?

### ISSUE THREAD

**Issue by Akikosophia** [Karima002/The-client-s-website#12]
Je was al goed op weg, je had de link op de juiste plek! 
Alleen de import ontbrak deze kun je boven aan in je css plaatsen

<img width="628" alt="Naamloos 32" src="https://github.com/user-attachments/assets/bcbfb49a-c676-4055-b403-a7bf12eb27e2">

<img width="652" alt="Naamloos 35" src="https://github.com/user-attachments/assets/f65ee48b-3bfb-4476-9ab7-7d890170b533">

**Comment by Karima002** [comment]
Commit 56a0e02: de volgende wijzigingen toegevoegd
 
- Google fonts gezocht en geplakt in HTML en CSS
https://github.com/Karima002/The-client-s-website/blob/56a0e023cf7a82eba71dedab78e5b89fa90862b3/index.html#L8-L12
