### ISSUE TITLE
code review [Nadia en Halima]

### ISSUE THREAD

**Issue by nadiachaja** [Karima002/The-client-s-website#3]
- Gebruik meer h2 t/m h6 elementen 
- Schrijf meer comments
- Gebruik h1 in de header

**Comment by joostf** [comment]
@nadiachaja tip voor de volgende keer; maak voor alle bevindingen een apart issue aan met ieder een betekenisvolle titel. Hiermee zorg je ervoor dat de lijst met issues overzichtelijker is.

**Comment by Karima002** [comment]
**Commit 36b5b4c**

De volgende bewerkingen zijn gedaan in de code:
- Comments toevoegen aan de header, main en footer.
