### ISSUE TITLE
Hoofdletters in img src

### ISSUE THREAD

**Issue by Robin1224** [Karima002/The-client-s-website#4]
Bij veel van de foto's op je pagina heb je een `src` attribuut waar de .png in hoofdletters staat.

https://github.com/Karima002/The-client-s-website/blob/1633a73e4acc9822d5bbfcc8c2fff66ef0149e12/index.html#L12

De extensie in het `src` attribuut is hoofdlettergevoelig, en als de .png dus als .PNG geschreven is, worden de assets niet meer herkend. Daarom werken de foto's op de pagina op dit moment niet.

Ook is het over het algemeen afgeraden om spaties in bestand namen te gebruiken, en zou je deze beter kunnen vervangen met bijvoorbeeld een _ of een -, maar ook met spaties werkt het nog wel, dus dit is niet per sé nodig.

**Suggestie:** de .PNG in de `src` attributen op je foto's te veranderen naar `.png`, zodat de foto's goed weergeven worden.

**Comment by Karima002** [comment]
**Commit 7ae0c85**

De volgende veranderingen zijn gedaan in de code:
- PNG verandert in png zodat de afbeeldingen werken
- Spaties in de titel van de foto's verwijderd en vervangen door  -
