### ISSUE TITLE
Heading als subtitle

### ISSUE THREAD

**Issue by Robin1224** [Karima002/The-client-s-website#5]
Bovenin het `<article>` element gebruik je volgens mij een `<h4>` element als een subtitel.

https://github.com/Karima002/The-client-s-website/blob/1633a73e4acc9822d5bbfcc8c2fff66ef0149e12/index.html#L39-L42

Het is afgeraden om heading elementen als subtitel te gebruiken, en je kunt hiervoor beter een element genaamd `<hgroup>` gebruiken. Dit element groepeert een` heading` en een `<p>` samen, om zo semantisch subtitels aan te geven. [Meer info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup)

**Suggestie:** Je kunt in dit geval de `<div>` dat om de `<h1>` en `<h4>` heen staat veranderen naar een `<hgroup>` element, en dan de `<h4>` omzetten naar een `<p>`. Dit zou er bijvoorbeeld zo uit kunnen zien:

```html
<hgroup class="article-text"> 
    <h1>Verbindend, fris en vol energie: een duik in de opkomst van maté</h1> 
    <p>Maté-frisdranken winnen aan populariteit in Nederland. Als alternatief voor gangbare energiedranken, is maté vooral gewild in creatieve en bewuste kringen. Waar komt deze groei vandaan? </p> 
</hgroup> 
```

**Comment by Karima002** [comment]
**Commit 34a6f74**

De volgende veranderingen zijn toegevoegd in de code:
- Het verwijderen van de section om de h1, h4 en img
- Het verwijderen van de div
- Het toevoegen van een hgroup om de h1 en p (de img staat nu buiten de hgroup)

Met een hgroup presenteer je een header en gerelateerde content. Dit heb ik verder kunnen lezen op: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup](url)

Mijn code ziet er nu als volgt uit: 
https://github.com/Karima002/The-client-s-website/blob/34a6f7493bb275adb2d560c7bdf4ab52fae3b806/index.html#L45-L51
