### ISSUE TITLE
Valideer je HTML

### ISSUE THREAD

**Issue by joostf** [Karima002/The-client-s-website#6]
Als je regelmatig je HTML valideert kan je makkelijk zien waar nog fouten in de structuur of syntax van de HTML zitten!
https://validator.w3.org/nu/?doc=https%3A%2F%2Fkarima002.github.io%2FThe-client-s-website%2F

**Comment by Karima002** [comment]
**Commit 2256218**

De validator gaf inderdaad een aantal fouten aan:
- Het hebben van spaties in image namen
- Een verkeerd gesloten `</p>`
- Het schrijven van en alt-attribute in een `<img>` tag

Deze fouten zijn nu opgelost!
