### ISSUE TITLE
Maak logo klikbaar

### ISSUE THREAD

**Issue by joostf** [Karima002/The-client-s-website#7]
https://github.com/Karima002/The-client-s-website/blob/1633a73e4acc9822d5bbfcc8c2fff66ef0149e12/index.html#L12

Het is gebruikelijk om een logo klikbaar te maken. Zodat je ten alle tijden terug kan naar de begin pagina

**Comment by Karima002** [comment]
Commit 63ac3de

De code ziet er nu als volgt uit:

https://github.com/Karima002/The-client-s-website/blob/63ac3de30daf701cd42c8c7e1d6054551886421f/index.html#L16-L17
