### ISSUE TITLE
Layout in CSS

### ISSUE THREAD

**Issue by Clarice-COD** [Karima002/The-client-s-website#8]
Het is makkelijker om een `flexbox` in de navigatie te gebruiken inplaats van een `display: inline block;`. Bij de nieuwsbrief en de doneer knop staat er nu een`float`, Misschien is `flex` beter voor in de plaats? Daarnaast is het beter om het logo naar `flexbox` om te zetten. En als laatst maak je best veel gebruik van `pixels`, `rem` is beter. 

Verder ben je goed onderweg :)

**Comment by irisvw** [comment]
![IMG_1973](https://github.com/user-attachments/assets/1cebc07c-a7ca-4de9-9318-3aff03a55e72)
wat ideetjes om dingen te positioneren met flex ipv text-align en floats :)

**Comment by Karima002** [comment]
Commit 267011b

Flexbox in mijn navigatie gebruikt:
https://github.com/Karima002/The-client-s-website/blob/267011b6e6a54b5ca8bb37878ebe0d4ae4852d3d/styles/styles.css#L12-L29

Resultaat:
![resu](https://github.com/user-attachments/assets/564ff432-5951-4bf3-99d4-903ef7362df3)
